name: assets
description: A sample command-line application.
version: 1.0.0
homepage: https://github.com/changleibox/assets

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
 path: ^1.7.0
 sprintf: ^5.0.0
 args: ^1.6.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4

executables:
  assets:
